### ISSUE TITLE
Apply "Hall Rules and Conventions of Academic Writing"

### ISSUE THREAD

**Issue by nopara73** [nopara73/ZeroLink#11]
[Hall Rules and Conventions of Academic Writing](https://drhazelhall.files.wordpress.com/2013/01/2013_hall_rules-conventions_ac_writing.pdf)  

- [ ] Rule 1: You must write in sentences
- [x] Rule 3: You must use appropriate punctuation
- [x] Rule 5: You must use the apostrophe correctly and with care
- [x] 1. Style conventions:  numbers and dates; capitals; print enhancements; abbreviations; typing and spelling
- [ ] 2. Tone conventions: formal, jargon and cliché-free, impersonal writing
- [ ] 3. Forming arguments: how to turn your information into a well-written essay or report 

# ToDo

## Random refactoring
Fix them by using search function or other tools:  
- [x] Numbers below one hundred are usually written in full. Numbers above one hundred may be presented by digits.  
- [x] Dates are usually given in the conventional combinations of numbered day, named month and
numbered year. Punctuation is not required.  
- [x] Avoid using "also", "besides" and "but". You may use "in addition" or "however".
- [x] Avoid using dash, semi-colon and explanation mark.  
- [x] Avoid using contraction apostrope.
- [x] Avoid using brackets.
- [x] [Avoid personal language](http://library.bcu.ac.uk/learner/writingguides/1.21.htm) (I, my, mine, we, our, us, you, author)  

## Sentences
Go through all sentences one by one and correct them according to the following:  
- [ ] Does it start with capital letter?  
- [ ] Does it end with a full stop, exclamation mark or question mark?
- [ ] Does it contain a verb?
- [ ] Is it long? Break it into short sentences.  
- [ ] Does it make sense if it were read out independently of the sentence before and after it?
- [ ] Does it contain abbrevation? Don't use them.
- [ ] Is it repetition or waffle? ("As explained above", "already mentioned", etc..) Avoid the use if if.

## Paragraphs
Go through all the paragraphs and pay attention to:  
Paragraphs should normally be between 50 words minimum and 200 words maximum in
length.  
The recommended organisation of a typical paragraph is:  
1. opening topic sentence, i.e. main point given  
2. explanation of topic sentence  
3. supporting sentences that explain its significance
4. discussion of examples or evidence (citing authorities; drawing on empirical
evidence, i.e. research carried out by others or, in the case of a dissertation, you;
drawing on your own experience, for example from placement)
5. concluding sentence
